<?php

function import_node_import_info() {
  global $user;
  $language = language_default();
  $info['node'] = array(
    'keys' => array(
      'nid' => 'Node Id',
      'title' => 'Title',
    ),
    'fields' => array(
      'nid' => 'Node Id',
      'title' => 'Title',
      'body' => 'Body',
      'created' => 'Created',
      'published' => 'Published',
      'sticky' => 'Sticky',
      'promote' => 'Promoted',
    ),
    'defaults' => array(
      'type' => variabe_get('import_node_default_node_type', 'page'),
      'language' => $language->language,
      'uid' => $user->uid,
      'name' => $user->name, 
    ),
  );
}

function import_node_merge(&$object, $data) {
  $info = import_node_import_info();
  if($object_type == 'node'){
    foreach(array_keys($info['node']['fields']) as $key) {
      $object->$key = $data[$key];
    }
  }
}

function import_node_object_save($object_type, $object) {
  if($object_type == 'node'){
    node_save($object);
  }
}

