<?php
/**
 * @file
 * Importing nodes is done here 
 */

/**
 * Implement hook_import_info()
 */
function import_node_import_info() {
  $info = array(
    'type' => 'node',
    'keys' => array(
      'nid' => 'Node Id',
      'title' => 'Title',
    ),
    'fields' => array(
      'nid' => 'Node Id',
      'title' => 'Title',
      'body' => 'Body',
      'created' => 'Created',
      'published' => 'Published',
      'sticky' => 'Sticky',
      'promote' => 'Promoted',
    ),
    'workflow' => array(
      'fields' => import_node_workflow_fields(),
      'callbacks' => '',
    ),
  );
  return $info;
}

/**
 * Form elements for the work flow
 * @return array $form
 */
function import_node_workflow_fields() {
  
}

/**
 * Implement hook_import_object()
 */
function import_node_import_object($object_type, $data, $op) {
  if($object_type == 'node') {
    switch($op) {
      case 'create':
        return import_node_node_defaults();
      case 'load':
      	return node_load(array($data['key'] => $data['value']));
    }  
  }
}

/**
 * Implement hook_import_merge()
 */
function import_node_import_merge($object_type, &$object, $data) {
  if($object_type == 'node'){
    foreach($data as $key => $value) {
      $object->$key = $value;
    }
  }
}

/**
 * Implement hook_import_save()
 */
function import_node_import_save($object_type, $object) {
  if($object_type == 'node'){
    node_save($object);
  }
}

/**
 * Create a default node 
 * @return object $node 
 */
function import_node_node_defaults() {
  global $user;
  $language = language_default();
  $node = new stdClass;
  $node->vid = NULL;
  $node->type = variable_get('import_node_default_node_type', 'page');
  $node->language = $language->language;
  $node->uid = $user->uid;
  $node->name = $user->name;
  $node->taxonomy = array();
  return $node;
}

