<?php
/**
 * @file
 * Importing nodes is done here.
 * You should extend this module if you're importing nodes with more information
 */

include('import_merge_node.pages.inc');

/**
 * Implement hook_merge()
 */
function import_merge_node_merge($type, &$node, $data, $meta = NULL) {
  if($type == 'node'){
    foreach($data as $key => $value) {
      $object->$key = $value;
    }
  }
}

/**
 * Create a default profile
 * @return object $profile
 */
function import_merge_node_merge_profile() {
  $profile = new stdClass;
  $profile->name = NULL;
  $profile->type = 'node';
  $profile->overwrite = FALSE;
  $profile->create_new = TRUE;
  $profile->data = array();
  $profile->get_callback = 'import_merge_node_node_load';
  $profile->set_callback = 'import_merge_node_node_save';
  $profile->create_callback = 'import_merge_node_node_new';
  $profile->get_data_key = NULL;
  $profile->meta = NULL;
  return $profile;
}

function import_merge_node_node_load($data, $meta = NULL) {
  return node_load($data);
}

function import_merge_node_node_save($node, $meta = NULL) {
  node_save($node);
}

/**
 * Create a default node 
 * @return object $node
 */
function import_merge_node_node_new() {
  global $user;
  $language = language_default();
  $node = new stdClass;
  $node->vid = NULL;
  $node->type = variable_get('import_node_default_node_type', 'page');
  $node->language = $language->language;
  $node->uid = $user->uid;
  $node->name = $user->name;
  $node->taxonomy = array();
  return $node;
}



