<?php
/**
 * @file
 * Importing nodes is done here 
 */

define("IMPORT_MERGE_NODE_TYPE", 'node');

/**
 * Implement hook_im()
 */
function import_merge_node_im() {
  $info = array(
    'type' => IMPORT_MERGE_NODE_TYPE,
    'keys' => array(
      'nid' => 'Node Id',
      'title' => 'Title',
    ),
    'fields' => array(
      'nid' => 'Node Id',
      'title' => 'Node Title',
      'body' => 'Body',
      'created' => 'Created',
      'published' => 'Published',
      'sticky' => 'Sticky',
      'promote' => 'Promoted',
    ),
  );
  return $info;
}


/**
 * Implement hook_im_init()
 */
function import_merge_node_im_init($object_type, $data, $op, $meta = NULL) {
  if(import_merge_is_node_type($object_type)) {
    switch($op) {
      case 'create':
        return import_merge_node_node_defaults();
      case 'load':
      	return node_load(array($data['key'] => $data['value']));
    }  
  }
}

/**
 * Implement hook_im_merge()
 */
function import_merge_node_im_merge($object_type, &$object, $data) {
  if(import_merge_is_node_type($object_type)){
    foreach($data as $key => $value) {
      $object->$key = $value;
    }
  }
}

/**
 * Implement hook_im_save()
 */
function import_merge_node_im_save($object_type, $object) {
  if(import_merge_is_node_type($object_type)){
    node_save($object);
  }
}

/**
 * Create a default node 
 * @return object $node 
 */
function import_merge_node_node_defaults() {
  global $user;
  $language = language_default();
  $node = new stdClass;
  $node->vid = NULL;
  $node->type = variable_get('import_node_default_node_type', 'page');
  $node->language = $language->language;
  $node->uid = $user->uid;
  $node->name = $user->name;
  $node->taxonomy = array();
  return $node;
}

/**
 * Is this object the right type?
 * @param string $object_type
 * @return boolean 
 */
function import_merge_is_node_type($object_type) {
  return $object_type == IMPORT_MERGE_NODE_TYPE;
}


