<?php
/**
 * @file
 * Importing taxonomy data is done here 
 */

define("IMPORT_MERGE_TAXONOMY_TYPE", 'term');

/**
 * Implement hook_im_ui_profile()
 */
function import_merge_taxonomy_im_ui_profile() {
  $info['taxonomy_term'] = array(
    'description' => t('Taxonomy Term Import'),
    'type' => IMPORT_MERGE_TAXONOMY_TYPE,
    'form' => 'import_merge_taxonomy_form'
  );
  return $info;
}

/**
 * Implement hook_im_init()
 */
function import_merge_taxonomy_im_init($object_type, $data, $op, $meta = NULL) {
  $vid = $meta['form_values']['vid'];
  if(empty($vid)) {
    return;
  }
  if(import_merge_is_taxonomy_type($object_type)) {
    switch($op) {
      case 'create':
      	$term = new stdClass;
        $term->vid = $vid;
        $term->name = '';
        $term->description = '';
        $term->weight = 0;
        return $term;
        	    
      case 'load':
        switch($data['key']) {
          case 'tid':
            return taxonomy_get_term($data['value']);
          case 'name':
            return taxonomy_get_term_by_name($data['value']);
      }
    }  
  }
}

/**
 * Implement hook_im_merge()
 */
function import_merge_taxonomy_im_merge($object_type, &$object, $data) {
  if(import_merge_is_taxonomy_type($object_type)){
    foreach($data as $key => $value) {
      $object->$key = $value;
    }
  }
}

/**
 * Implement hook_im_save()
 */
function import_merge_taxonomy_im_save($object_type, $object) {
  if(import_merge_is_taxonomy_type($object_type)){
    $term = (array) $object;
    taxonomy_save_term($term);
  }
}

/**
 * Get the vocabs for merge. 
 * @return array  
 */
function import_merge_taxonomy_get_vocabularies() {
  $vocabularies = array();
  foreach(taxonomy_get_vocabularies() as $vocabulary) {
    $vocabularies[$vocabulary->vid] = $vocabulary->name;
  }
  return $vocabularies;
}

/**
 * Is this object the right type?
 * @param string $object_type
 * @return boolean 
 */
function import_merge_is_taxonomy_type($object_type) {
  return $object_type == IMPORT_MERGE_TAXONOMY_TYPE;
}



