<?php

function import_taxo_importapi(&$node, $data) {
  $fields = array_keys(_import_taxo_get_fields());
  $taxo = array();
  $vocab = variable_get('import_taxo_vocabs', array());
  foreach($fields as $key => $field) {
    if(!empty($data[$field])) {
      $taxo[] = $data[$field];
    }
  }
  $taxo_path = taxo_get_tax_path($taxo, $vocab[0]);
  $last = $taxo_path[count($taxo_path)-1];
  $term = taxonomy_get_term($last);
  $node->taxonomy = array($term);
}

function import_taxo_form_alter(&$form, $form_state, $form_id) {
  switch($form_id) {
    case 'import_form_file_fields':
      $form['fields']['#options'] += _import_taxo_get_fields();
      break;
  }
}

function taxo_get_tax_path($taxo, $vid) {
  $path = array();
  $taxo_tree = taxonomy_get_tree($vid);
  foreach($taxo as $key => $value) {
    $parent = ($key == 0) ? '0' : $path[$key-1];
    foreach($taxo_tree as $term){
      if($term->parents[0] == $parent && $term->name == $taxo[$key]){
        $path[] = $term->tid;
      }
    }
  }
  return $path;
}


function _import_taxo_get_fields() {
  $fields = array();
  foreach(range(0, variable_get('import_taxo_depth', 3)-1) as $i) {
    $fields['taxonomy-'. $i] = 'Taxonomy Level '. ($i + 1);
  }
  return $fields;
}
