<?php
/**
 * 
 * @file
 * 
 * An import API that grabs data from a file and delegates to other module
 * for merging with objects such as nodes, users of taxonomy terms.
 * 
 * Written by Rimian Perkins
 * @see http://www.rimian.com.au
 * @see http://drupal.org/user/96072
 * Released under GNU LESSER GENERAL PUBLIC LICENSE
 * @see http://drupal.org/LICENSE.txt
 * Please buy me beer if you use this module and happen to be around when I am drinking a beer
 * @see http://www.coopers.com.au
 */

include('import.file.inc');

/**
 * Implementation of hook_menu() 
 */
function import_menu() {
  $items = array();
  $items['import'] = array(
    'title' => 'Import Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_form'),
    'access arguments' => array('import content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['import/fields'] = array(
    'title' => 'Import Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_form_fields'),
    'access arguments' => array('import content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm() 
 */
function import_perm() {
  return array('import content');
}

function import_form($form_state) {
  $file = $form_state['post']['file'];
  $form = array();
  
  $options = array();
  foreach(import_get_files() as $file_object) {
    $options[$file_object->filename] = $file_object->basename;
  }
  
  $form['files'] = array(
    '#type' => 'fieldset',
    '#title' => 'Files',
    '#collapsible' => TRUE,
    '#description' => 'Your import path is: ' . import_get_file_path(),
  );
  $form['files']['file'] = array(
    '#type' => 'radios',
    '#options' => $options,
  );
  $form['type'] = array(
    '#type' => 'select',
    '#title' => t('Load or Create Object Type'),
    '#description' => 'This is the type of object that gets loaded or created with the import data. It could be a node, user or taxonomy term',
    '#options' => _import_get_object_types(),
  );
  $form['key'] = array(
    '#type' => 'select',
    '#title' => 'Update Key',
    '#description' => 'Load and update items matching this key.',
    '#default_value' => variable_get('import_default_key', ''),
    '#options' => array('<none>') + _import_get_keys(),
  );
  //TODO: hook workflow
  $form['workflow'] = array(
    '#type' => 'fieldset',
    '#title' => 'Work Flow',
    '#collapsible' => TRUE,
  );
  $form['workflow']['skip-new'] = array(
    '#type' => 'checkbox',
    '#title' => 'Skip new rows',
    '#description' => 'Skip rows that are not matched with the above ' . $form['key']['#title'],
    '#default_value' => variable_get('import_default_skip_new', 0),
  );
  $form['workflow']['skip-existing'] = array(
    '#type' => 'checkbox',
    '#title' => 'Skip existing rows',
    '#description' => 'Skip rows that match with the above the above ' . $form['key']['#title'],
    '#default_value' => variable_get('import_default_skip_existing', 0),
  );
  /*
  $form['workflow']['new-published'] = array(
    '#type' => 'checkbox',
    '#title' => 'Published',
    '#description' => 'New nodes are set set to Published if this is checked.',
    '#default_value' => variable_get('import_default_new_published', 1),
  );
  */
  $form['preview'] = array(
    '#type' => 'button',
    '#value' => 'Preview File',
    '#submit' => 'import_preview_rows',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
    '#attributes' => array('onclick' => '
      var form = document.getElementById(\'import-form\');
      form.action = \'import/fields\';
      '),
  );
  if(!empty($file)) {
    $form['rows'] = array(
      '#type' => 'item',
      '#value' => import_preview_rows($file, 20),
    );
  }
  return $form;
}

function import_preview_rows($file, $limit) {
  $header = import_file_to_array($file, 'header');
  $rows = import_file_to_array($file, 'list', $limit);
  return theme('table', $header, $rows, array('style' => 'font-size: 0.8em;'));
}

/**
 * Form alter this one to add fields to the CSV import
 */
function import_form_file_fields($form_state) {
  $form['fields'] = array(
    '#type' => 'select',
    '#options' => _import_get_fields(),
  );
  return $form;
}

function import_form_fields($form_state) {
  
  //expose this to other modules through nested form: 'import_form_file_fields'
  $file_fields = drupal_retrieve_form('import_form_file_fields', $form_state);
  drupal_prepare_form('import_form_file_fields', $file_fields, $form_state);
  
  $form = array();
  if(empty($form_state['post']['file'])){
    return $form;
  }
  foreach(array('file', 'key', 'skip-new', 'skip-existing', 'type', 'new-published') as $hidden) {
    $form[$hidden] = array('#type' => 'hidden', '#value' => $form_state['post'][$hidden],);
  }
  foreach(import_file_to_array($form_state['post']['file'], 'header') as $key => $col) {
    if(!empty($col)) {
      $do_it = TRUE;
      $form['field-'.$key] = $file_fields['fields'];
      $form['field-'.$key]['#title'] = $col;
    }
  }
  if($do_it) {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Do it',
    );
  }
  return $form;
}

/**
 * Implement hook_submit
 */
function import_form_fields_submit($form, &$form_state) {
  //TODO: factor out implementation and delegate 
  $limit = variable_get('import_row_limit', 0);
  $fields = _import_get_form_field_keys_value($form_state['values']);
  $rows = import_file_to_array($form_state['values']['file'], 'skip-header', $limit, $fields);
  $object_type = $form_state['values']['type'];
  foreach($rows as $row) {
    $row = array_combine($fields, $row);
    $key = $form_state['values']['key'];
    if(empty($form_state['values']['skip-existing'])) {
      $object = import_invoke_object($object_type, array('key' => $key, 'value' => $row[$key]), 'load');
    } 
    if(!$object && empty($form_state['values']['skip-new'])) {
      $object = import_invoke_object($object_type, $row, 'create');
    }
    import_invoke_merge($object_type, $object, $row);
    import_invoke_save($object_type, $object);
  }
  drupal_set_message('Imported!', 'status', FALSE);
}

/**
 * Load information about contributed modules
 * @return array 
 */
function import_invoke_info() {
  $info = array();
  $hook = 'import_info';
  foreach (module_implements($hook) as $module) {
    $module_info = call_user_func($module .'_'. $hook);
    if (isset($info) && is_array($info)) {
      $info = array_merge($info, $module_info);
    }
  }
  return $info;
}

/**
 * Save an object
 */
function import_invoke_save($object_type, $object) {
  $hook = 'import_save';
  foreach (module_implements($hook) as $name) {
    $function = $name .'_'. $hook;
    $function($object_type, $object);
  }
}

/**
 * Merge the imported data with the object
 */
function import_invoke_merge(&$object, $data) {
  $hook = 'import_merge';
  foreach (module_implements($hook) as $name) {
    $function = $name .'_'. $hook;
    $function($object, $data);
  }
}

/**
 * Load or create a new object
 * @param string $object_type
 * @param $data
 * @param string $op
 */
function import_invoke_object($object_type, $data, $op) {
  $hook = 'import_object';//TODO: consider refactoring this hook
  foreach (module_implements($hook) as $name) {
    $function = $name .'_'. $hook;
    $object = $function($object_type, $data, $op);
    if(!empty($$object)){
      return $object;
    }
  } 
  return FALSE;
}

function _import_get_form_field_keys_value($values) {
  $keys = array();
  for($i = 0; $i < count(import_file_to_array($values['file'], 'header')); $i++) {
    $field = $values['field-'. $i];
    if(!empty($field)) {
      $keys[$i] = $field;
    }
  }
  return $keys;
}

function _import_get_keys() {
  $keys = array();
  foreach(import_invoke_info() as $info) {
    $keys = array_merge($keys, array_combine($info['keys'], $info['keys'])); 
  }
  return $keys;
}

function _import_get_object_types() {
  $types = array_keys(import_invoke_info());
  return array_combine($types, $types);
}

function _import_get_fields() {
  $info = import_invoke_info();
  return $info['fields'];
}

function _import_tidy_data($data) {
  $tidy_data = array();
  foreach($data as $col){
    $tidy_data[] = trim(check_plain($col));
  }
  return $tidy_data;
}

