<?php
/**
 * 
 * @file
 * 
 * An import API that grabs data from a file and delegates to other module
 * for merging with objects such as nodes, users of taxonomy terms.
 * 
 * Written by Rimian Perkins
 * @see http://www.rimian.com.au
 * @see http://drupal.org/user/96072
 * Released under GNU LESSER GENERAL PUBLIC LICENSE
 * @see http://drupal.org/LICENSE.txt
 * Please buy me beer if you use this module and happen to be around when I am drinking a beer
 * @see http://www.coopers.com.au
 */

include('import.file.inc');

/**
 * Implementation of hook_menu() 
 */
function import_menu() {
  $items = array();
  $items['import'] = array(
    'title' => 'Import Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_form'),
    'access arguments' => array('import content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['import/fields'] = array(
    'title' => 'Import Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_form_fields'),
    'access arguments' => array('import content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_perm() 
 */
function import_perm() {
  return array('import content');
}

/**
 * The first form. Choose a file and work flow options. 
 */
function import_form($form_state) {
  $file = $form_state['post']['file'];
  $form = array();
  
  $info = import_get_info();

  $file_options = array();
  foreach(import_get_files() as $file_object) {
    $file_options[$file_object->filename] = $file_object->basename;
  }

  $form['files'] = array(
    '#type' => 'fieldset',
    '#title' => 'Files',
    '#collapsible' => TRUE,
    '#description' => 'Your import path is: ' . import_get_file_path(),
  );
  $form['files']['file'] = array(
    '#type' => 'radios',
    '#options' => $file_options,
  );
  $form['type'] = array(
    '#type' => 'select',
    '#title' => t('Object Type'),
    '#description' => 'This is the type of object that gets loaded or created with the import data',
    '#options' => _import_form_options($info['types']),
  );
  $form['key'] = array(
    '#type' => 'select',
    '#title' => 'Update Key',
    '#description' => 'Load and update objects matching this key.',
    '#default_value' => variable_get('import_default_key', ''),
    '#options' => _import_form_options($info['keys'], array('<none>')),
  );
  $form['workflow'] = array(
    '#type' => 'fieldset',
    '#title' => 'Work Flow',
    '#collapsible' => TRUE,
  );
  $form['workflow']['create-new'] = array(
    '#type' => 'checkbox',
    '#title' => 'Create new data',
    '#description' => 'Create new objects, if they don\'t exist from the imported data',
    '#default_value' => variable_get('import_default_create_new', 1),
  );
  $form['workflow']['overwrite'] = array(
    '#type' => 'checkbox',
    '#title' => 'Overwrite existing objects',
    '#description' => 'Overwrite existing objects loaded with this data',
    '#default_value' => variable_get('import_default_skip_existing', 0),
  );
  $form['preview'] = array(
    '#type' => 'button',
    '#value' => 'Preview File',
    '#submit' => 'import_preview_rows',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Next',
    '#attributes' => array('onclick' => '
      var form = document.getElementById(\'import-form\');
      form.action = \'import/fields\';
      '),
  );
  if(!empty($file)) {
    $form['rows'] = array(
      '#type' => 'item',
      '#value' => import_preview_rows($file, 20),
    );
  }
  return $form;
}

function import_preview_rows($file, $limit) {
  $header = import_file_to_array($file, 'header');
  $rows = import_file_to_array($file, 'list', $limit);
  return theme('table', $header, $rows, array('style' => 'font-size: 0.8em;'));
}

/**
 * The second form. This matches rows with object info 
 */
function import_form_fields($form_state) {
  
  $form = array();
  if(empty($form_state['post']['file'])){
    return $form;
  }
  foreach(array('file', 'key', 'create-new', 'overwrite', 'type', 'new-published') as $hidden) {
    $form[$hidden] = array('#type' => 'hidden', '#value' => $form_state['post'][$hidden],);
  }

  $info = import_get_info($form_state['post']['type']);
  
  foreach(import_file_to_array($form_state['post']['file'], 'header') as $key => $col) {
    if(!empty($col)) {
      $do_it = TRUE;
      $form['field-'.$key] = array(
        '#title' => $col,
        '#type' => 'select',
        '#options' => array('Ignore') + $info['fields'],
      );
      $form['field-'.$key]['#title'] = $col;
    }
  }
  if($do_it) {
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Do it',
    );
  }
  return $form;
}

/**
 * Implement hook_submit()
 */
function import_form_fields_submit($form, &$form_state) {
  //TODO: delegate making of rows?
  //TODO: abstract this controller 
  $fields = _import_get_form_field_keys_value($form_state['values']);
  $rows = import_file_to_array($form_state['values']['file'], 'skip-header', variable_get('import_row_limit', 0), $fields);
  $object_type = $form_state['values']['type'];
  $key = $form_state['values']['key'];
  foreach($rows as $data) {
    $data = array_combine($fields, $data);
    $object = NULL;
    if(!empty($key) && !empty($form_state['values']['overwrite'])) {
      $object = import_invoke_object($object_type, array('key' => $key, 'value' => $data[$key]), 'load');
    } 
    if(!$object && !empty($form_state['values']['create-new'])) {
      $object = import_invoke_object($object_type, $data, 'create');
    }
    if(!empty($object)) {
      import_invoke_merge($object_type, $object, $data);
      import_invoke_save($object_type, $object);
    }
  }
  drupal_set_message('Imported!', 'status', FALSE);
}

/**
 * The interface to import_invoke_info()
 * @param string $object_type
 * @return array $info all the info for this type or all types
 */
function import_get_info($object_type = NULL) {
  $info = array(
    'types' => array(),
    'keys' => array(),
    'fields' => array(),
    'workflow' => array(),
  );
  foreach(import_invoke_info() as $module_info) {
    if(is_null($object_type) || $module_info['type'] == $object_type) {
      //TODO: eeeww!
      $info['types'][$module_info['type']] = $module_info['type'];
      if(is_array($module_info['keys'])) $info['keys'] = array_merge($info['keys'], $module_info['keys']);
      if(is_array($module_info['fields'])) $info['fields'] = array_merge($info['fields'], $module_info['fields']);
      if(is_array($module_info['workflow'])) $info['workflow'] = array_merge($info['workflow'], $module_info['workflow']);
    }
  }
  return $info;
}

/**
 * Load information about contributed modules
 * 
 * You should not call this function directly.
 * @see import_get_object_info()
 * 
 * @return array 
 */
function import_invoke_info() {
  $info = array();
  $hook = 'import_info';
  foreach (module_implements($hook) as $module) {
    $info[] = call_user_func($module .'_'. $hook);
  }
  return $info;
}

/**
 * Save an object
 */
function import_invoke_save($object_type, $object) {
  $hook = 'import_save';
  foreach (module_implements($hook) as $module) {
    call_user_func($module .'_'. $hook, $object_type, $object);
  }
}

/**
 * Merge the imported data with the object
 * @param string $object_type 
 * @param object $object. A node, user or anything
 * @param array $data. A data row from the file
 */
function import_invoke_merge($object_type, &$object, $data) {
  $hook = 'import_merge';
  foreach (module_implements($hook) as $module) {
    call_user_func($module .'_'. $hook, $object_type, &$object, $data);
  }
}

/**
 * Load or create a new object
 * @param string $object_type
 * @param $data
 * @param string $op
 */
function import_invoke_object($object_type, $data, $op) {
  $hook = 'import_object';//TODO: consider refactoring this hook
  foreach (module_implements($hook) as $module) {
    $object = call_user_func($module .'_'. $hook, $object_type, $data, $op);
    if(!empty($object)){
      return $object;
    }
  } 
  return FALSE;
}

/**
 * Get the user values for each info key  
 */
function _import_get_form_field_keys_value($values) {
  $keys = array();
  for($i = 0; $i < count(import_file_to_array($values['file'], 'header')); $i++) {
    $field = $values['field-'. $i];
    if(!empty($field)) {
      $keys[$i] = $field;
    }
  }
  return $keys;
}

function _import_form_options($options, $first = NULL) {
  if(is_array($options) && is_array($first)) {
    $options = $first + $options;
  }
  return array_combine($options, $options);
}

function _import_tidy_data($data) {
  $tidy_data = array();
  foreach($data as $col){
    $tidy_data[] = trim(check_plain($col));
  }
  return $tidy_data;
}


